title: InvCtrl
description: Inventory Control System berbasis web (FastAPI)
baseurl: "/invctrl"
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:

author:
  name: Gand0r
  email: portgash.the.ace@gmail.com

url: "https://gand0r.github.io"
